### ISSUE TITLE
LMMs/GLMMs

### ISSUE THREAD

**Issue by TarandeepKang** [bstatcomp/bayes4psy#5]
Dear All,

I have just read your paper in Front Psychol. Do you have any plans to add LMM and GLMM functionality?

Thanks & Best Wishes,

Tarandeep Kang

**Comment by demsarjure** [comment]
Hi!

We plan to keep developing the library by implementing new models and upgrading the functionality of existing ones. The addition of LMM/GLMM is definitely something worth a consideration. Unfortunately, all of the researchers that work on bayes4psy are currently busy with higher priority projects. So at this point I cannot give a timeline about when the next upgrade will be executed and what exactly will be in it.

For the time being maybe the rstanarm library can help you out. It is probably the best library for executing Bayesian regressions.

Cheers, Jure
